import HelpCenterClient from "@/components/help/help-center-client";

export const metadata = {
  title: "Help Center – Scanzy AI Support, FAQs & Troubleshooting",
  description:
    "Need help using Scanzy AI tools? Visit our Help Center for FAQs, guides, troubleshooting, account setup, billing info, and support resources.",
  keywords: [
    "Scanzy AI help center",
    "Scanzy support page",
    "Scanzy AI FAQ",
    "how to use Scanzy AI",
    "Scanzy billing help",
    "Scanzy subscription",
    "Scanzy cancel subscription",
    "Scanzy account setup",
    "Scanzy scan failed",
    "Scanzy AI tool issues",
    "Scanzy refund request",
    "Scanzy pricing questions",
    "Scanzy AI detection explanation",
    "AI plagiarism detection help",
    "Scanzy user guide",
    "Scanzy beginner tutorial",
    "Scanzy payment method",
    "Scanzy error support",
    "Scanzy scan issues",
    "Scanzy report understanding",
    "Scanzy AI false positive",
    "Scanzy detection accuracy",
    "AI content explanation",
    "Scanzy AI usage tips",
    "Scanzy tool tutorial",
    "Scanzy troubleshooting steps",
    "Scanzy how it works",
    "Scanzy feature guide",
    "AI scanner instructions",
    "fix Scanzy issues",
    "Scanzy how to scan",
    "Scanzy scan blocked",
    "Scanzy detection guide",
    "Scanzy plan options",
    "Scanzy upgrade plan",
    "Scanzy contact help",
    "Scanzy tool not loading",
    "Scanzy browser issues",
    "Scanzy compatibility",
    "Scanzy for writers",
    "Scanzy for bloggers",
    "Scanzy for developers",
    "Scanzy for university students",
    "Scanzy AI tool broken",
    "Scanzy scanner guide",
    "Scanzy rewrite help",
    "Scanzy originality score meaning",
    "Scanzy AI prompt help",
    "Scanzy refund steps",
    "Scanzy cancellation process",
    "Scanzy auto-renew info",
    "Scanzy account problem",
    "Scanzy support email",
    "Scanzy live help",
    "Scanzy chatbot help",
    "Scanzy AI vs GPTZero",
    "Scanzy feature comparison",
    "Scanzy vs other tools",
    "Scanzy AI update log",
    "Scanzy API help",
    "Scanzy onboarding",
    "Scanzy customer support",
    "Scanzy form guide",
    "Scanzy feedback link",
    "Scanzy website issues",
    "Scanzy mobile problem",
    "Scanzy desktop app",
    "Scanzy subscription expired",
    "Scanzy documentation",
    "Scanzy technical help",
    "Scanzy knowledge base",
    "Scanzy video guide",
    "Scanzy tutorial help",
    "Scanzy premium support",
    "Scanzy query form",
    "Scanzy onboarding guide",
    "Scanzy email not working",
    "Scanzy AI report PDF",
    "Scanzy insights guide",
    "Scanzy score accuracy",
    "Scanzy detection strength",
    "Scanzy user manual",
    "Scanzy AI user experience",
  ],
  openGraph: {
    title: "Scanzy Help Center – AI Tools FAQ, Support & Guide",
    description:
      "Explore Scanzy AI's help center for frequently asked questions, setup guides, payment info, and support for detection and rewrite tools.",
    url: "https://scanzy.fun/help",
    siteName: "Scanzy AI",
    type: "website",
    images: [
      {
        url: "https://scanzy.fun/og-image.png",
        width: 1200,
        height: 630,
        alt: "Scanzy Help Center Open Graph Image",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Scanzy AI Help & Support – FAQs, Tutorials, Guides",
    description:
      "Need help with Scanzy AI? Browse FAQs, common issues, guides, and contact support from the official Scanzy Help Center.",
    images: ["https://scanzy.fun/og-image.png"],
  },
  alternates: {
    canonical: "https://scanzy.fun/help",
  },
};

export default function HelpCenterPage() {
  return <HelpCenterClient />;
}
